### ISSUE TITLE
在chrome上无法使用的问题

### ISSUE THREAD

**Issue by yunnysunny** [LingyuCoder/SkyRTC-demo#1]
在win8.1 chrome34下加入房间后，看不到视频画面。在android4.1 chrome34下，加入房间后，浏览器崩溃了。

**Comment by zwssunny** [comment]
我是能用就是退出chrom时，服务器报错
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25)
怎么解决，别的浏览器不会出错
