### ISSUE TITLE
server.js不能运行

### ISSUE THREAD

**Issue by qiuliangflash** [LingyuCoder/SkyRTC-demo#2]
你好，我已经下载了代码，然后安装了nodejs的库，express，ws，和node-uuid，但是发现还是不能运行，错误是：module.js:340
    throw err;
          ^
Error: Cannot find module 'skyrtc'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/raul_qiu/Downloads/SkyRTC-demo-master/server.js:4:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

谢谢

**Comment by Hsueh-Jen** [comment]
這是我第一次在github上留言，我只能說這範例太棒了，感謝分享！

**Comment by liuyuqingenglish** [comment]
你好 我也遇到过这个问题。但是我已经添加了这个模块 skyrtc。下面是错误列表
Error: Cannot find module 'skyrtc'
    at Function.Module._resolveFilename (module.js:4
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\lyq-pc\Desktop\W
ver.js:4:32)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

这是我电脑的 安装的模块 列表。能解答一下么  谢谢
C:\Windows\system32>npm list -g --depth 0
E:\Program Files\nodejs\Module_Globle
+-- express@4.14.1
+-- node-uuid@1.4.7
+-- skyrtc@0.0.2
`-- ws@2.1.0

**Comment by lx2328** [comment]
执行node server.js之后没有任何响应了，依赖是通过npm install 安装的

**Comment by zhenyiyi** [comment]
@liuyuqingenglish 环境变量配置错了吧。
