### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by oliango** [LingyuCoder/SkyRTC-demo#9]
D:\pj\SkyRTC-demo-master\node_modules\ws\index.js:9
const WebSocket = require('./lib/WebSocket');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\pj\SkyRTC-demo-master\node_modules\skyrtc\SkyRTC.js:1:85)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

报错是什么问题

**Comment by Tchoumi** [comment]
````test with this  CLI:  node --harmony app.js````
